language: node_js
node_js:
- '6'
install:
- npm install -g resume-cli
before_script: 
- cd cv
script:
- resume export cv.html
after_success:
  - cd $TRAVIS_BUILD_DIR
  - eval "$(ssh-agent -s)" #start the ssh agent
  - echo "$DEPLOY_KEY" > deploy_key.pem
  - chmod 600 deploy_key.pem # this key should have push access
  - ssh-add deploy_key.pem
  - git add cv/*
  - git commit -m "commit from travis build n° $TRAVIS_JOB_NUMBER"
  - git remote add deploy vcanuel/vcanuel.github.io
  - git push deploy master
