language: node_js
node_js:
- '6'
before_install:
- openssl aes-256-cbc -K $encrypted_7902bf38939f_key -iv $encrypted_7902bf38939f_iv
  -in .travis/id_rsa_travis.enc -out .travis/id_rsa_travis -d
install:
- npm install -g resume-cli
script:
- cd cv
- resume export cv_vcanuel.html
after_success:
- cd $TRAVIS_BUILD_DIR
- eval "$(ssh-agent -s)"
- chmod 600 .travis/id_rsa_travis
- ssh-add .travis/id_rsa_travis
- git remote add github git@github.com:vcanuel/vcanuel.github.io.git
- git add cv/cv_vcanuel.html
- git config user.name "Travis CI"
- git config user.email "nobody@nobody.org"
- git commit -m "commit from travis build number $TRAVIS_JOB_NUMBER [ci skip]"
- git config --global push.default simple
- git push github HEAD:master  --force
