language: node_js
node_js:
- '6'
install:
- npm install -g resume-cli
before_script:
- cd cv
script:
- resume export cv.html
after_success:
- cd $TRAVIS_BUILD_DIR
- eval "$(ssh-agent -s)"
- chmod 600 .travis/id_rsa_travis
- ssh-add .travis/id_rsa_travis
- git remote add deploy vcanuel/vcanuel.github.io
- git add cv/*
- git commit -m "commit from travis build number $TRAVIS_JOB_NUMBER"
- git push deploy master
dd:
- openssl aes-256-cbc -K $encrypted_7902bf38939f_key -iv $encrypted_7902bf38939f_iv
  -in id_rsa_travis.enc -out .travis/id_rsa_travis -d
